### ISSUE TITLE
One player can dominate and track down anyone

### ISSUE THREAD

**Issue by Reader8765** [pydude/Stikk.io#26]
This game in this stage is not balanced enough. If people team up, they can easily take the lead and keep it by using the map to find people, killing the same people repeatedly. The game needs another factor that stops people from staying that powerful.

**Comment by pydude** [comment]
Well, if people team up on of them will probably backstab the other. 
But I do agree that if a person becomes too powerful, they can sometimes dominate the server.
A possible thing is that several weaker players can gang up the leader to take him down.
Maybe removing other players from the minimap besides the leader and you. That way, people can track down the leader, but the leader can't track down them.

**Comment by Reader8765** [comment]
It is extremely hard to gang up on a leader with a flamethrower. Maybe you could remove it like Epic Games removed the Zapatron 2.0 from Fortnite? Basically, you might add it back in later when the balance of powerful weapons leans in it's favor.

**Comment by Reader8765** [comment]
I like the idea with the leader on the mini-map. He could be represented with a crown or something like that.

**Comment by pydude** [comment]
Fixed with minimap players not visible to 1st, 2nd, or 3rd.
