### ISSUE TITLE
Game Throwing Error in Touchscreen Mode

### ISSUE THREAD

**Issue by Reader8765** [pydude/Stikk.io#37]
Error: `Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>`.

**Comment by pydude** [comment]
This is not a problem. This error has no effect whatsoever. Visiting the URL leads to https://www.chromestatus.com/features/5093566007214080. 
It states 
> ... that calls to preventDefault will be ignored 

The call to preventDefault is there to stop the game's canvas from being scrolled. In Chrome, it is not needed, but in some other browsers (mostly mobile) it is.

**Comment by Reader8765** [comment]
You could prevent this by checking for Chrome and not using it if true:
`const isChrome = !!window.chrome && !!window.chrome.webstore;`
