### ISSUE TITLE
New Ranged weapon system

### ISSUE THREAD

**Issue by pydude** [pydude/Stikk.io#5]
Having a ranged weapon that is powerful will be problematic. Low-level players cannot escape before they are shot down. 
Possible solutions:
- Make ranged weapons really weak
- Make an ammo system so that you need to buy ammo periodically to continue shooting,
- Make it so you stop and reload every X number of shots. The X varies over different weapons.

**Comment by pydude** [comment]
Going to use reload system!
Every weapon has a certain number of ammo. Once it shoots this many, you go slow (~0.1 speed) while you  wait to reload. Different weapons take different time to reload. While reloading, the weapon's art will change (clip gone, lights off, etc). 
There will be a display on your screen showing how much ammo you have remaining. On mobile, tap it to reload. On keyboard press a key (maybe r?).

**Comment by pydude** [comment]
The system is now complete!

**Comment by Reader8765** [comment]
This is still a problem. The flamethrower is too overpowered even with the reloading.
